# Enable Powerline
set-option -g status-position bottom
set -g default-terminal "tmux-256color"

# Change refreshing tmux config 
unbind r
bind r source-file ~/.config/tmux/tmux.conf

# Change to Ctrl + S instead of Ctrl + B
set -g prefix C-s

# Resize panes with the mosue
set -g mouse on

# Start windows and panes at index 1
set -g base-index 1
set-window-option -g pane-base-index 1
set -g renumber-windows on

# Use HJKL for Left, Down, Up, Right instead of the arrow keys
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# Catppuccin
set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "rounded"
set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_session}"
set -ag status-right "#{E:@catppuccin_status_application}"
set -ag status-right "#{E:@catppuccin_status_uptime}"
set -agF status-right "#{E:@catppuccin_status_battery}"
set -g @catppuccin_window_default_text "#W"
set -g @catppuccin_window_current_text "#W"
set -g @catppuccin_window_text "#W"
run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux

# List of Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'

# set -g @plugin 'erikw/tmux-powerline'
# set -g @plugin 'arcticicestudio/nord-tmux'

# TMUX Plugin Manager - ALWAYS AT THE BOTTOM
run '~/.config/tmux/plugins/tpm/tpm'
